#!/usr/bin/env fish
#
# Fetches binary package.
#
# Usage:
# xbps-get PKGNAME
#
# Can be called outside of distdir.

if test (count $argv) != 1
	echo usage: xbps-get pkgname
	exit 1
end

pushd (xdistdir)
set pkgname $argv[1]
set pkgver (./xbps-src show $pkgname | grep -Po '^version:\s+\K.+')
set pkgrev (./xbps-src show $pkgname | grep -Po '^revision:\s+\K.+')
set arch (./xbps-src show $pkgname | grep -Po '^archs:\s+\Knoarch'; or uname -m)
if set -q XBPS_TARGET_ARCH
	set arch $XBPS_TARGET_ARCH
end
set repository (echo (grep repository= srcpkgs/$pkgname/template | cut -d= -f2 | tr -d '"'"'")/)
if string match '*-musl' $arch
	set repository musl/$repository
end
popd
set filename $pkgname'-'$pkgver'_'$pkgrev'.'$arch'.xbps'
set url 'https://mirror.clarkson.edu/voidlinux/current/'$repository$filename
curl -f $url -o $filename
or begin
	echo Failed to download $url
	false
end
